### PR TITLE
Fixed Channel Viewer ordering for channels with capital letters

### LINKED ISSUE #52: Wrong Channel order CVP in JSON
It still doesn't order the channels the right way (http://i.imgur.com/2JJdZrO.png). As you can see at the bottom, STFU and "Small Talk" should be swapped.

Here's another screenshot with the mumble client on the right and the CV on the left: http://i.imgur.com/Std0Wfk.png

Both channels are set at Position=0.
If I put Position=1 for STFU, it will be at the good place.
If I change STFU to Stfu, it will be at the good place.

So I think that the compare also compares the case. The capital letters are before the non-capital letters in the ascii table which might be the problem.

### PR DESCRIPTION
**Pull request by nicolasjoly**
This should fix #52

### CODE REVIEW

**Comment by Kissaki** [comment]
If we do not want natural order, it may be easier to use `strcmp`.

**Comment by nicolasjoly** [comment]
This fix puts the natural order by making all letters in lowercase, making sure that the case of the letter doesn't interfere with the sorting. This makes the sorting exactly the same as Mumble.

**Comment by Kissaki** [comment]
This will not guarantee `testa` being placed before `testA`.

**Comment by nicolasjoly** [comment]
Ok I see what you mean.

**Comment by Kissaki** [comment]
I started on something that is also unicode aware (mb_ and stuff) for non-ASCII/international characters.

**Comment by Kissaki** [comment]
Closed in favour of b9c986ada1cc91287cbd3e6662ab77ef0614898d

**Pull request closed without merging**
