### PR TITLE
Modification of codebase to work with Ice 3.7 and PHP 7.4

### PR DESCRIPTION
**Pull request by tinyhaggis**
I've completed my initial work to refactor the codebase of Mumpi to fully work with Ice 3.7.

I have tested the functionality of the application and I'm not seeing any errors when I add users, register, do admin update tasks to server details or anything else like that.

I'd appreciate any feedback on this if there are still issues identified.  It'd also be good if this could be merged into the master branch if no problems are found.  Let me know if you want to use a branch other than *master*.

### CODE REVIEW

**Comment by Kissaki** [comment]
Thank you very much for your efforts.

Could you do one pass over your commits and clean them up?

It looks like 7f68b97f54ba218de0a24446f4ce2d9054154e39 is a temporary commit to find a solution, 0bac88714b519c0e09ede798ac9ab6ea43b0fdeb too.  
0bac88714b519c0e09ede798ac9ab6ea43b0fdeb adds gitignores when it supposedly (only) temporarily disables functionality.

Thank you. :)

I may not test the functionality in the end, but I will look over the code, and trust in your testing as you document/voice it. I will definitely merge it like that if it looks reasonable.

**Comment by Kissaki** [comment]
If there is no reason to split the `Converting to Ice 3.7 Syntax` commits then squashing them would be nice too.

**Comment by Kissaki** [comment]
Scrolling over the commit list, I guess I’ll give my reasoning/broader thoughts on my change request. :)

I can see the commits stem from a development workflow, discovering and implementing a solution.

For documenting changes and landing changes that’s not a very helpful thing though. It’s difficult for a reviewer (me in this case) to get and overview and follow the changes.

So it’s a good idea to, after finding a reasonable solution and suggesting it in an MR, to clean up the work-commits into more logical, cleaned up and documented commits. That’ll make it much easier to read, argue about, and as such documents it better for the future (in the code history).

**Comment by Kissaki** [comment]
@AtomicHaggis I was just want to make sure I did not irritate you off?

I see you closed the PR, and seemingly dropped the commits from the PR source branch. Are you planning to come back with a new PR?

**Comment by AtomicHaggis** [comment]
@Kissaki I pulled it down as I need to better organise the source and squash the commits before submitting a PR.  I've got a few other adjustments that I will make with removal of old code before I push it back so I'll resubmit the PR when I have free time to sort that out.

**Pull request closed without merging**
